### ISSUE TITLE
Apache configuration

### ISSUE THREAD

**Issue by ctreton** [docker-taiga/taiga#28]
Hi,
First of all I'm not used to Nginx, I have a debian server with apache2 server who reverse proxy to taiga docker container with Nginx.
SSL is enable.
It works for front but webservice and back doesn't.
I have a 406 code for websocket and 502 for the back.
Here is the console error reporting :
<details><summary>Error</summary>
<p>

```http
GET https://taiga.mydomain.com/api/v1/stats/discover 502 (Bad Gateway)
GET https://taiga.mydomain.com/api/v1/projects?discover_mode=true&order_by=-total_fans_last_week 502 (Bad Gateway)
GET https://taiga.mydomain.com/api/v1/projects?discover_mode=true&order_by=-total_activity_last_week 502 (Bad Gateway)
GET https://taiga.mydomain.com/api/v1/projects?discover_mode=true&is_featured=true 502 (Bad Gateway)
WebSocket connection to 'wss://taiga.mydomain.com/events/' failed: Error during WebSocket handshake: Unexpected response code: 426
```

</p>
</details>

Here is my Apache configuration :
<details><summary>mydomain.conf</summary>
<p>

```apache
<VirtualHost *:80>
    ServerName taiga.mydomain.com
    ServerAdmin dev@mydomain.com

    Redirect / https://taiga.mydomain.com/
</VirtualHost>

<VirtualHost *:443>
    ServerName taiga.mydomain.com
    ServerAdmin dev@mydomain.com

    Header Set X-Robots-Tag "noindex, nofollow, noarchive, nosnippet"

    SetOutputFilter SUBSTITUTE,DEFLATE

    SSLProxyEngine On
    ProxyPreserveHost On
    ProxyPass         / https://localhost:3002/
    ProxyPassReverse  / https://localhost:3002/

    AddOutputFilterByType SUBSTITUTE text/html
    Substitute "s|https://localhost:3002/|https://taiga.mydomain.com/|i"

    ErrorLog ${APACHE_LOG_DIR}/taiga_error.log
    CustomLog ${APACHE_LOG_DIR}/taiga_access.log combined

    SSLCertificateFile /etc/letsencrypt/live/taiga.mydomain.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/taiga.mydomain.com/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf
    <Proxy *>
        Order deny,allow
        Allow from all
        Allow from localhost
    </Proxy>
</VirtualHost>
```

</p>
</details>

Here is my Nginx configuration :
<details><summary>nginx.conf</summary>
<p>

```nginx
server {
	server_name taiga.mydomain.com;
	listen 80;
	location / {
		return 302 https://$server_name$request_uri;
	}
}

server {
	server_name taiga.mydomain.com;
	listen 443 ssl;
	ssl_certificate /taiga-cert/fullchain.pem;
	ssl_certificate_key /taiga-cert/privkey.pem;

	location ^~ /events {
		proxy_pass http://events:8888/;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_connect_timeout 7d;
		proxy_send_timeout 7d;
		proxy_read_timeout 7d;
	}

	location ^~ /api {
		include proxy_params;
		proxy_pass http://back;
	}

	location ^~ /admin {
		include proxy_params;
		proxy_pass http://back;
	}

	location ^~ /static {
		include proxy_params;
		proxy_pass http://back;
	}

	location ^~ /media {
		include proxy_params;
		proxy_pass http://back;
	}

	location / {
		include proxy_params;
		proxy_pass http://front;
	}
}
```

</p>
</details>

And here is the docker compose configuration :
<details><summary>docker-compose.yml</summary>
<p>

```yml
version: '3'

services:
  back:
    image: dockertaiga/back
    container_name: taiga-back
    restart: unless-stopped
    depends_on:
      - db
      - events
    networks:
      - default
    volumes:
      - ./data/media:/taiga-media
      - ./conf/back:/taiga-conf
    env_file:
      - variables.env

  front:
    image: dockertaiga/front
    container_name: taiga-front
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./conf/front:/taiga-conf
    env_file:
      - variables.env

  db:
    image: postgres:11-alpine
    container_name: taiga-db
    restart: unless-stopped
    networks:
      - default
    env_file:
      - variables.env
    volumes:
      - ./data/db:/var/lib/postgresql/data

  rabbit:
    image: dockertaiga/rabbit
    container_name: taiga-rabbit
    restart: unless-stopped
    networks:
      - default
    env_file:
      - variables.env

  events:
    image: dockertaiga/events
    container_name: taiga-events
    restart: unless-stopped
    depends_on:
      - rabbit
    networks:
      - default
    env_file:
      - variables.env

  proxy:
    image: dockertaiga/proxy
    container_name: taiga-proxy
    restart: unless-stopped
    depends_on:
      - back
      - front
      - events
    networks:
      - default
    ports:
      - 3002:443
      - 3003:80
    volumes:
      - /etc/letsencrypt/live/taiga.mydomain.com/:/taiga-cert
      - /etc/letsencrypt/archive/:/archive
      - ./conf/proxy:/taiga-conf
    env_file:
      - variables.env

networks:
  default:
```

</p>
</details>

Any ideas ?
