### ISSUE TITLE
Problem with TAIGA_HOST env variable.

### ISSUE THREAD

**Issue by xNero321** [docker-taiga/taiga#34]
Hi.

I just cloned your repository to start taiga on my VPS.
Once i figured out that ```TAIGA_HOST``` was not modified in the container.
I tried to change it in the file ```variables.env```. 

So i tried to set the variable directly in the compose file.
Everything is working fine now, you did a good job.
However, is it possible that when i change the variable in the env file, the ```TAIGA_HOST``` in the container is also changed, rather than adding an env variable in the compose file ?

```
 front:
    image: dockertaiga/front:5.0.7
    container_name: taiga-front
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./conf/front:/taiga-conf
    environment:
    - TAIGA_HOST=taiga.mydomain.com
    env_file:
      - variables.env
```
